
-- create INSERTHUMIDITYORIGINAL table to store original humidity data
  CREATE TABLE "INSERTHUMIDITYORIGINAL" 
   (	"DT" DATE, 
	"PORTLAND" NUMBER(10,4), 
	"SAN_FRANCISCO" NUMBER(10,4), 
	"SEATTLE" NUMBER(10,4), 
	"LOS_ANGELES" NUMBER(10,4), 
	"SAN_DIEGO" NUMBER(10,4), 
	"LAS_VEGAS" NUMBER(10,4), 
	"PHOENIX" NUMBER(10,4), 
	"ALBUQUERQUE" NUMBER(10,4), 
	"DENVER" NUMBER(10,4), 
	"SAN_ANTONIO" NUMBER(10,4), 
	"DALLAS" NUMBER(10,4), 
	"HOUSTON" NUMBER(10,4), 
	"KANSAS_CITY" NUMBER(10,4), 
	"MINNEAPOLIS" NUMBER(10,4), 
	"SAINT_LOUIS" NUMBER(10,4), 
	"CHICAGO" NUMBER(10,4), 
	"NASHVILLE" NUMBER(10,4), 
	"INDIANAPOLIS" NUMBER(10,4), 
	"ATLANTA" NUMBER(10,4), 
	"DETROIT" NUMBER(10,4), 
	"JACKSONVILLE" NUMBER(10,4), 
	"CHARLOTTE" NUMBER(10,4), 
	"MIAMI" NUMBER(10,4), 
	"PITTSBURGH" NUMBER(10,4), 
	"PHILADELPHIA" NUMBER(10,4), 
	"NEW_YORK" NUMBER(10,4), 
	"BOSTON" NUMBER(10,4)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "CISETS" ;

--create INSERTPRESSUREORIGINAL table to store original pressure data 
  CREATE TABLE "INSERTPRESSUREORIGINAL" 
   (	"DT" DATE, 
	"PORTLAND" NUMBER(10,4), 
	"SAN_FRANCISCO" NUMBER(10,4), 
	"SEATTLE" NUMBER(10,4), 
	"LOS_ANGELES" NUMBER(10,4), 
	"SAN_DIEGO" NUMBER(10,4), 
	"LAS_VEGAS" NUMBER(10,4), 
	"PHOENIX" NUMBER(10,4), 
	"ALBUQUERQUE" NUMBER(10,4), 
	"DENVER" NUMBER(10,4), 
	"SAN_ANTONIO" NUMBER(10,4), 
	"DALLAS" NUMBER(10,4), 
	"HOUSTON" NUMBER(10,4), 
	"KANSAS_CITY" NUMBER(10,4), 
	"MINNEAPOLIS" NUMBER(10,4), 
	"SAINT_LOUIS" NUMBER(10,4), 
	"CHICAGO" NUMBER(10,4), 
	"NASHVILLE" NUMBER(10,4), 
	"INDIANAPOLIS" NUMBER(10,4), 
	"ATLANTA" NUMBER(10,4), 
	"DETROIT" NUMBER(10,4), 
	"JACKSONVILLE" NUMBER(10,4), 
	"CHARLOTTE" NUMBER(10,4), 
	"MIAMI" NUMBER(10,4), 
	"PITTSBURGH" NUMBER(10,4), 
	"PHILADELPHIA" NUMBER(10,4), 
	"NEW_YORK" NUMBER(10,4), 
	"BOSTON" NUMBER(10,4)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "CISETS" ;

-- create INSERTTEMPERATUREORIGINAL table to store original temperature data
  CREATE TABLE "INSERTTEMPERATUREORIGINAL" 
   (	"DT" DATE, 
	"PORTLAND" NUMBER(10,4), 
	"SAN_FRANCISCO" NUMBER(10,4), 
	"SEATTLE" NUMBER(10,4), 
	"LOS_ANGELES" NUMBER(10,4), 
	"SAN_DIEGO" NUMBER(10,4), 
	"LAS_VEGAS" NUMBER(10,4), 
	"PHOENIX" NUMBER(10,4), 
	"ALBUQUERQUE" NUMBER(10,4), 
	"DENVER" NUMBER(10,4), 
	"SAN_ANTONIO" NUMBER(10,4), 
	"DALLAS" NUMBER(10,4), 
	"HOUSTON" NUMBER(10,4), 
	"KANSAS_CITY" NUMBER(10,4), 
	"MINNEAPOLIS" NUMBER(10,4), 
	"SAINT_LOUIS" NUMBER(10,4), 
	"CHICAGO" NUMBER(10,4), 
	"NASHVILLE" NUMBER(10,4), 
	"INDIANAPOLIS" NUMBER(10,4), 
	"ATLANTA" NUMBER(10,4), 
	"DETROIT" NUMBER(10,4), 
	"JACKSONVILLE" NUMBER(10,4), 
	"CHARLOTTE" NUMBER(10,4), 
	"MIAMI" NUMBER(10,4), 
	"PITTSBURGH" NUMBER(10,4), 
	"PHILADELPHIA" NUMBER(10,4), 
	"NEW_YORK" NUMBER(10,4), 
	"BOSTON" NUMBER(10,4)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "CISETS" ;


-- create INSERTWEATHER_DESCORIGINAL table to store original weather_description data
CREATE TABLE "INSERTWEATHER_DESCORIGINAL" 
   (	"DT" DATE, 
	"PORTLAND" VARCHAR2(50 BYTE), 
	"SAN_FRANCISCO" VARCHAR2(50 BYTE), 
	"SEATTLE" VARCHAR2(50 BYTE), 
	"LOS_ANGELES" VARCHAR2(50 BYTE), 
	"SAN_DIEGO" VARCHAR2(50 BYTE), 
	"LAS_VEGAS" VARCHAR2(50 BYTE), 
	"PHOENIX" VARCHAR2(50 BYTE), 
	"ALBUQUERQUE" VARCHAR2(50 BYTE), 
	"DENVER" VARCHAR2(50 BYTE), 
	"SAN_ANTONIO" VARCHAR2(50 BYTE), 
	"DALLAS" VARCHAR2(50 BYTE), 
	"HOUSTON" VARCHAR2(50 BYTE), 
	"KANSAS_CITY" VARCHAR2(50 BYTE), 
	"MINNEAPOLIS" VARCHAR2(50 BYTE), 
	"SAINT_LOUIS" VARCHAR2(50 BYTE), 
	"CHICAGO" VARCHAR2(50 BYTE), 
	"NASHVILLE" VARCHAR2(50 BYTE), 
	"INDIANAPOLIS" VARCHAR2(50 BYTE), 
	"ATLANTA" VARCHAR2(50 BYTE), 
	"DETROIT" VARCHAR2(50 BYTE), 
	"JACKSONVILLE" VARCHAR2(50 BYTE), 
	"CHARLOTTE" VARCHAR2(50 BYTE), 
	"MIAMI" VARCHAR2(50 BYTE), 
	"PITTSBURGH" VARCHAR2(50 BYTE), 
	"PHILADELPHIA" VARCHAR2(50 BYTE), 
	"NEW_YORK" VARCHAR2(50 BYTE), 
	"BOSTON" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "CISETS" ;


-- create INSERTWIND_SPEEDORIGINAL table to store original wind_speed data
CREATE TABLE "INSERTWIND_SPEEDORIGINAL" 
   (	"DT" DATE, 
	"PORTLAND" NUMBER, 
	"SAN_FRANCISCO" NUMBER, 
	"SEATTLE" NUMBER, 
	"LOS_ANGELES" NUMBER, 
	"SAN_DIEGO" NUMBER, 
	"LAS_VEGAS" NUMBER, 
	"PHOENIX" NUMBER, 
	"ALBUQUERQUE" NUMBER, 
	"DENVER" NUMBER, 
	"SAN_ANTONIO" NUMBER, 
	"DALLAS" NUMBER, 
	"HOUSTON" NUMBER, 
	"KANSAS_CITY" NUMBER, 
	"MINNEAPOLIS" NUMBER, 
	"SAINT_LOUIS" NUMBER, 
	"CHICAGO" NUMBER, 
	"NASHVILLE" NUMBER, 
	"INDIANAPOLIS" NUMBER, 
	"ATLANTA" NUMBER, 
	"DETROIT" NUMBER, 
	"JACKSONVILLE" NUMBER, 
	"CHARLOTTE" NUMBER, 
	"MIAMI" NUMBER, 
	"PITTSBURGH" NUMBER, 
	"PHILADELPHIA" NUMBER, 
	"NEW_YORK" NUMBER, 
	"BOSTON" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "CISETS" ;